# -*- coding: utf-8 -*-
"""Copy of SAVYAS YOLOV8m Working.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MQwBzsDM7F3OljyGrLYjdgceJOSvHB5S
"""

!nvidia-smi

import os
HOME = os.getcwd()
print(HOME)

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

!yolo mode=checks

from ultralytics import YOLO

from IPython.display import display, Image

# Commented out IPython magic to ensure Python compatibility.
!mkdir {HOME}/datasets
# %cd {HOME}/datasets

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="XROkBOp3fXs8NJvfuSo3")
project = rf.workspace("innodatatics1").project("pipe-inventory")
dataset = project.version(1).download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/datasets

# Commented out IPython magic to ensure Python compatibility.
# %cd {HOME}

!yolo task=detect mode=train model=yolov8m.pt data=/content/datasets/pipe-inventory-1/data.yaml epochs=10 imgsz=250 plots=True

!pip install ultralytics==8.0.134

from google.colab import drive
drive.mount('/content/drive')

!ls /content/runs/detect/train

from IPython.display import Image

Image(filename='/content/runs/detect/train/confusion_matrix.png', width=600)

Image(filename='/content/runs/detect/train/results.png', width=600)

Image(filename='/content/runs/detect/train/val_batch0_pred.jpg', width=600)

!yolo task=detect mode=val model=/content/runs/detect/train/weights/best.pt data=/content/datasets/pipe-inventory-1/data.yaml

!yolo predict mode=predict model=/content/runs/detect/train/weights/best.pt conf=0.25 source=/content/datasets/pipe-inventory-1/test/images save=True

import glob
from IPython.display import Image, display

for image_path in glob.glob('/content/runs/detect/predict/*.jpg')[:3]:
      display(Image(filename=image_path, width=600))
print("\n")

import pandas as pd

# Assuming df is your DataFrame
df.to_csv('machine_learning_results.csv', index=False)